/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import model.application;
import model.vitalsignhistory;
import javax.swing.JOptionPane;
/**
 *
 * @author megha
 */
public class createjpanel extends javax.swing.JPanel {
    private application application;

    /**
     * Creates new form createjpanel
     */
    public createjpanel() {
        initComponents();
    }
    createjpanel(application applcation){
        initComponents();
        this.application =application;
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldobservationid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldbloodpressure = new javax.swing.JTextField();
        fieldtemperature = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addobservationbtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create vital signs");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        add(fieldobservationid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setText("blood pressure");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        add(fieldbloodpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, -1));

        fieldtemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldtemperatureActionPerformed(evt);
            }
        });
        add(fieldtemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, -1));

        jLabel4.setText("temperature");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        addobservationbtn.setText("add observation");
        addobservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addobservationbtnActionPerformed(evt);
            }
        });
        add(addobservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addobservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addobservationbtnActionPerformed
    vitalsignhistory history = this.application.getHistory();
        
        // read the text fields
        
        String id = fieldobservationid.getText();
        String temperature = fieldtemperature.getText();
        String bloodPressure = fieldbloodpressure.getText();
        
        // convert/cast and pass
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(bloodPressure), Double.valueOf(temperature));
        
        JOptionPane.showMessageDialog(null, "Added your observation!");
    }//GEN-LAST:event_addobservationbtnActionPerformed

    private void fieldtemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldtemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldtemperatureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addobservationbtn;
    private javax.swing.JTextField fieldbloodpressure;
    private javax.swing.JTextField fieldobservationid;
    private javax.swing.JTextField fieldtemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
