/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.application;

/**
 *
 * @author megha
 */
public class mainjframe extends javax.swing.JFrame {

    /**
     * Creates new form mainjframe
     */
    
    application application;
    
    public mainjframe() {
        initComponents();
        
        this.application=new application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        createobsbtn = new javax.swing.JButton();
        viewvitalbtn = new javax.swing.JButton();
        medcatalogbtn = new javax.swing.JButton();
        assignmedbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createobsbtn.setText("create observation");
        createobsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createobsbtnActionPerformed(evt);
            }
        });

        viewvitalbtn.setText("view vital sign history");
        viewvitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewvitalbtnActionPerformed(evt);
            }
        });

        medcatalogbtn.setText("medicine catalog");
        medcatalogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medcatalogbtnActionPerformed(evt);
            }
        });

        assignmedbtn.setText("assign medicine");
        assignmedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmedbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createobsbtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewvitalbtn, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medcatalogbtn)
                    .addComponent(assignmedbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(createobsbtn)
                .addGap(27, 27, 27)
                .addComponent(viewvitalbtn)
                .addGap(18, 18, 18)
                .addComponent(medcatalogbtn)
                .addGap(18, 18, 18)
                .addComponent(assignmedbtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createobsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createobsbtnActionPerformed
        // TODO add your handling code here:
                jSplitPane1.setRightComponent(new createjpanel(this.application));

    }//GEN-LAST:event_createobsbtnActionPerformed

    private void viewvitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewvitalbtnActionPerformed
        // TODO add your handling code here:
                jSplitPane1.setRightComponent(new viewjpanel(this.application));

    }//GEN-LAST:event_viewvitalbtnActionPerformed

    private void medcatalogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medcatalogbtnActionPerformed
        // TODO add your handling code here:
                jSplitPane1.setRightComponent(new catalogjpanel(this.application));

    }//GEN-LAST:event_medcatalogbtnActionPerformed

    private void assignmedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmedbtnActionPerformed
        // TODO add your handling code here:
                jSplitPane1.setRightComponent(new medicineassignjpanel(this.application));

    }//GEN-LAST:event_assignmedbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainjframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainjframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignmedbtn;
    private javax.swing.JButton createobsbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medcatalogbtn;
    private javax.swing.JButton viewvitalbtn;
    // End of variables declaration//GEN-END:variables
}
