/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author megha
 */
public class viewjpanel extends javax.swing.JPanel {
    
    private Application application;
    DefaultTableModel viewtableModel;

    /**
     * Creates new form viewjpanel
     */
    public viewjpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldobservationid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldbloodpressure = new javax.swing.JTextField();
        fieldtemperature2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        updateobservationbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        observationtable = new javax.swing.JTable();
        viewdetailsbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View & Update vital signs");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));
        jPanel1.add(fieldobservationid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, -1));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setText("blood pressure");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel1.add(fieldbloodpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 70, -1));
        jPanel1.add(fieldtemperature2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, -1));

        jLabel4.setText("temperature");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        updateobservationbtn.setText("update observation");
        updateobservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateobservationbtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateobservationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        observationtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Temperature", "Blood Pressure"
            }
        ));
        jScrollPane1.setViewportView(observationtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        viewdetailsbtn.setText("view details");
        viewdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetailsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewdetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(575, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(331, 331, 331))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateobservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateobservationbtnActionPerformed
            // TODO add your handling code here:
            //update the observation object
                if (!fieldObservationID.getText().isEmpty()){
        if s
            
    }//GEN-LAST:event_updateobservationbtnActionPerformed
    public void displayObservations(){
        vitalsignhistory history=this.application.getHistory();
        if(history.getvitalsignhistory().size>0){
    }
    private void viewdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetailsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewdetailsbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldbloodpressure;
    private javax.swing.JTextField fieldobservationid;
    private javax.swing.JTextField fieldtemperature2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable observationtable;
    private javax.swing.JButton updateobservationbtn;
    private javax.swing.JButton viewdetailsbtn;
    // End of variables declaration//GEN-END:variables
}
